package kits

var FileContentTypeDict map[string]string = map[string]string{
	// 更多：https://www.runoob.com/http/http-content-type.html
	".avi":  "video/avi",
	".mp3":  "audio/mp3",
	".flac": "audio/flac",
	".m3u":  "audio/x-mpegurl",
	".m4a":  "audio/x-m4a",
	".webm": "video/webm",
	".wav":  "audio/x-wav",
	".mp4":  "video/mp4",
	".mkv":  "video/x-matroska",
	".wmv":  "video/x-ms-wmv",
	".asf":  "video/x-ms-asf",
	".rm":   "application/vnd.rn-realmedia",
	".rmvb": "application/vnd.rn-realmedia-vbr",
	".mov":  "video/quicktime",
	".m4v":  "video/mp4",
	".flv":  "video/x-flv",
	//
	".jpg":  "image/jpeg",
	".jpeg": "image/jpeg",
	".jpg2": "image/jpg2",
	".png":  "image/png",
	".gif":  "image/gif",
	".webp": "image/webp",
	".ico":  "image/ico",
	".tiff": "image/tiff",
	".tif":  "image/tiff",
	".bmp":  "image/bmp",
	".svg":  "image/svg+xml",
	//
	".html": "text/html; charset=utf-8",
	".txt":  "text/plain; charset=utf-8",
	".md":   "text/plain; charset=utf-8",
	".mod":  "text/plain; charset=utf-8",
	".css":  "text/css; charset=utf-8",
	".js":   "text/javascript; charset=utf-8",
	".xml":  "application/xml",
	".json": "application/json",
	".pdf":  "application/pdf",
	".doc":  "application/sword",
	".docx": "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
	".ppt":  "application/vnd.ms-powerpoint",
	".pptx": "application/vnd.openxmlformats-officedocument.presentationml.presentation",
	".xls":  "application/vnd.ms-excel",
	".xlsx": "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
	".epub": "application/epub+zip",
	".wps":  "application/kswps",
	".et":   "application/kset",
	".dps":  "application/ksdps",
	".psd":  "application/x-photoshop",
	".cdr":  "application/x-coreldraw",
	//
	".zip":  "application/zip",
	".7z":   "application/x-7z-compressed",
	".rar":  "application/vnd.rar",
	".exe":  "application/octet-stream",
	".dmg":  "application/zip",
	".app":  "application/zip",
	".ipa":  "application/iphone-package-archive",
	".apk":  "application/vnd.android.package-archive",
	".tar":  "application/x-tar",
	".tgz":  "application/x-tar",
	".gz":   "application/x-gzip",
	".gzip": "application/x-gzip",
}
